name: DoodStream Daily Uploader

on:
  schedule:
    - cron: '5 4 * * *'
  # This lets you run it manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run the DEBUGGER Script
        run: python upload.py

      # --- THIS IS THE NEW PART ---
      - name: Upload Debug Artifacts for Analysis
        # This 'if: always()' line is important. It makes sure the files are saved even if the script fails.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug_screenshot.png
            debug_page_content.html
      # --- END OF NEW PART ---
