name: DoodStream Daily Uploader

on:
  # This makes the script run automatically every day at 4:05 AM UTC.
  schedule:
    - cron: '5 4 * * *'
  # This allows you to run the script manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run the Uploader Script
        env:
          DOODSTREAM_API_KEY: ${{ secrets.DOODSTREAM_API_KEY }}
        run: python upload.py
